services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: subsense
      POSTGRES_PASSWORD: subsense_pw
      POSTGRES_DB: subsense
    ports:
      - "5433:5432"     # host 5433 -> container 5432
    volumes:
      - subsense_data:/var/lib/postgresql/data
volumes:
  subsense_data: